### PR TITLE
Femmes fatales

### PR DESCRIPTION
**Pull request by KA101**
This should swap in the updated Amazon sprites and an update (buff + sprite upgrade) to the Combat Succubus.

### CODE REVIEW

**Comment by KA101** [comment]
(Will re-do for A37.  Stand by.)

**Comment by KA101** [comment]
OK, A37 too.  If this breaks, it'll break for everyone!
:-/

**Comment by SoftMonster** [comment]
Great work.

**Comment by SoftMonster** [comment]
thanks

**Pull request merged**
